### ISSUE TITLE
This looks useful

### ISSUE THREAD

**Issue by minoseah629** [bjornmicallef/EscapeMines#1]
Hello,
I am reviewing this repo by following the link from one of your article. https://itsnotbugitsfeature.com/2021/04/30/integration-testing-a-net-core-console-application/

This article seems helpful, but I am curious as the debugging experience with testing in mind.  

I updated csproj files to 7.0 to help me ensure when I try this in my own project, I would not see any issues.

**Comment by bjornmicallef** [comment]
Hi minoseah629, let me know if there are any issues debugging the project

**Comment by minoseah629** [comment]
i took another approach.  but was promising work.
